### ISSUE TITLE
Add Minimum to ResourceInputs to improve Warehouses.

### ISSUE THREAD

**Issue by Chronovore** [fishpondstudio/CivIdle#59]
I suggest adding a minimum to the  IResourceInput to allow warehouses to operate in a more intuitive way.  In this way, we could add a Minimum value to keep in reserve, which is how cap acts currently.  This would allow the warehouse to keep pulling up to cap, but also allow other buildings to pull when the value is above minimum.

I attempted to build locally and create a PR, but for some reason I'm not able to setup my dev environment correctly.

**Comment by insraq** [comment]
Thanks, the game currently requires some special setup, which I haven't got time to document yet.

Regarding this, I have done something similar in Industry Idle. The problem is that this creates a loop: A resource will be pulled from a warehouse and then pulled back to the same warehouse. It actually causes more problems than solves. That why warehouses' cap works as is currently.

**Comment by insraq** [comment]
0.3.0
