### ISSUE TITLE
Choose Which Resource(s) to Supply when Construct/Upgrade a Building

### ISSUE THREAD

**Issue by insraq** [fishpondstudio/CivIdle#76]

**Comment by apierzch** [comment]
Rather than choosing I would suggest removing limitation of single resource transportation. Why shouldn't it be possible to transport both wood and stone when both are needed, but available in low amounts (so not using up all workers).

Just by reading the code and without running it (so I could be totally wrong) it seems like changing this line to return false could solve it: https://github.com/fishpondstudio/CivIdle/blob/180d92f8807590460d0d76721988f0270c68e6c0/shared/logic/Update.ts#L199

It would allow to continue looping over all required resources and (if workers and resources are still available) transport them all.

**Comment by insraq** [comment]
I think you misunderstood this ticket. You can transport two if you choose two.

**Comment by apierzch** [comment]
I see. Looks like you're trying to solve a different need than I had in mind. Maybe there is a way to target both.

Need 1: disable importing a resource for a while so that it can be used for other buildings (is this what you have in mind?)
How: being able to filter which resources should be transfered and which should be ignored
Challenge: priorities kind of address this already, at least partially

Need 2: transport 2nd resource on the list even if first is unavailable
Need 3: transport more than 1 resource if their availability is low and many workers are available

I feel like you are trying to address need (1) and I'm trying to address need (2) and (3). Or maybe the way you think of this would address (2) and (3) as well?
Or maybe there is a simple way of addressing (2) and (3) and then (1) is no longer so important

Just food for thought, don't mean to put any pressure or criticise your idea :)

**Comment by insraq** [comment]
> I see. Looks like you're trying to solve a different need than I had in mind. Maybe there is a way to target both.
> 
> Need 1: disable importing a resource for a while so that it can be used for other buildings (is this what you have in mind?)
> How: being able to filter which resources should be transfered and which should be ignored
> Challenge: priorities kind of address this already, at least partially
> 
> Need 2: transport 2nd resource on the list even if first is unavailable
> Need 3: transport more than 1 resource if their availability is low and many workers are available
> 
> I feel like you are trying to address need (1) and I'm trying to address need (2) and (3). Or maybe the way you think of this would address (2) and (3) as well?
> Or maybe there is a simple way of addressing (2) and (3) and then (1) is no longer so important
> 
> Just food for thought, don't mean to put any pressure or criticise your idea :)

Thanks. It's absolutely okay to criticize my idea. In the end, I want the best ideas in the game 😁

And now I get your point. But yes, as part of this ticket, I will also make the builder capacity split more flexibility. If you don't have enough specific resource, the residual capacity can be used for other resources
